version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]
    ports:
      - "18080:8080"
    volumes:
      - ./.containers/identity:/opt/keycloak/data

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: persondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  userapi:
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    container_name: userapi
    depends_on:
      - postgres
      - keycloak
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__default=Host=postgres;Port=5432;Database=persondb;Username=postgres;Password=postgrespw
    ports:
      - "8082:8080"
    restart: always

volumes:
  pgdata:
