version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: persondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  userapi:
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    container_name: userapi
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__default=Host=postgres;Port=5432;Database=persondb;Username=postgres;Password=postgrespw
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata:
